[
phases.setup
]
nixPkgs = ["python311"]

[
phases.install
]
cmds = ["python -m pip install poetry", "poetry install"]

[
start
]
cmd = "uvicorn src.political_discourse_analyzer.core.main:app --host 0.0.0.0 --port $PORT"