[build]
builder = "nixpacks"
buildCommand = "poetry install"

[deploy]
startCommand = "uvicorn src.political_discourse_analyzer.core.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.variables]
PYTHON_VERSION = "3.11"